-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 16:47:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hw4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hw4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hw4` DEFAULT CHARACTER SET utf8 ;
USE `hw4` ;

-- -----------------------------------------------------
-- Table `hw4`.`Owners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw4`.`Owners` ;

CREATE TABLE IF NOT EXISTS `hw4`.`Owners` (
  `OwnerID` INT NOT NULL,
  `OwnerName` VARCHAR(45) NOT NULL,
  `OwnerPhone` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`OwnerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hw4`.`Pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw4`.`Pets` ;

CREATE TABLE IF NOT EXISTS `hw4`.`Pets` (
  `PetID` INT NOT NULL,
  `OwnerID` INT NOT NULL,
  `PetName` VARCHAR(45) NOT NULL,
  `PetBreed` VARCHAR(45) NOT NULL,
  `ColorMarkings` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Gender` VARCHAR(5) NOT NULL,
  `NeuteredSpayed` VARCHAR(45) NOT NULL,
  `Owners_OwnerID` INT NOT NULL,
  PRIMARY KEY (`PetID`, `Owners_OwnerID`),
  CONSTRAINT `fk_Pets_Owners1`
    FOREIGN KEY (`Owners_OwnerID`)
    REFERENCES `hw4`.`Owners` (`OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pets_Owners1_idx` ON `hw4`.`Pets` (`Owners_OwnerID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hw4`.`Trainers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw4`.`Trainers` ;

CREATE TABLE IF NOT EXISTS `hw4`.`Trainers` (
  `TrainerID` INT NOT NULL,
  `TrainerName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TrainerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hw4`.`Classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw4`.`Classes` ;

CREATE TABLE IF NOT EXISTS `hw4`.`Classes` (
  `ClassID` INT NOT NULL,
  `ClassName` VARCHAR(45) NOT NULL,
  `ClassDescription` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`ClassID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hw4`.`TrainingEvents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hw4`.`TrainingEvents` ;

CREATE TABLE IF NOT EXISTS `hw4`.`TrainingEvents` (
  `ClassTime` DATETIME NOT NULL,
  `ClassID` INT NOT NULL,
  `PetID` INT NOT NULL,
  `TrainerID` INT NOT NULL,
  `Pets_PetID` INT NOT NULL,
  `Pets_Owners_OwnerID` INT NOT NULL,
  `Trainers_TrainerID` INT NOT NULL,
  `Classes_ClassID` INT NOT NULL,
  PRIMARY KEY (`ClassTime`, `Pets_PetID`, `Pets_Owners_OwnerID`, `Trainers_TrainerID`, `Classes_ClassID`),
  CONSTRAINT `fk_TrainingEvents_Pets1`
    FOREIGN KEY (`Pets_PetID` , `Pets_Owners_OwnerID`)
    REFERENCES `hw4`.`Pets` (`PetID` , `Owners_OwnerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrainingEvents_Trainers1`
    FOREIGN KEY (`Trainers_TrainerID`)
    REFERENCES `hw4`.`Trainers` (`TrainerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TrainingEvents_Classes1`
    FOREIGN KEY (`Classes_ClassID`)
    REFERENCES `hw4`.`Classes` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TrainingEvents_Pets1_idx` ON `hw4`.`TrainingEvents` (`Pets_PetID` ASC, `Pets_Owners_OwnerID` ASC) VISIBLE;

CREATE INDEX `fk_TrainingEvents_Trainers1_idx` ON `hw4`.`TrainingEvents` (`Trainers_TrainerID` ASC) VISIBLE;

CREATE INDEX `fk_TrainingEvents_Classes1_idx` ON `hw4`.`TrainingEvents` (`Classes_ClassID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;